version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3003:3000"
    # Load all environment variables from .env.local file for runtime
    env_file:
      - .env.local
    environment:
      # Override for production deployment
      - NODE_ENV=production
    # Enable connection to host machine services  
    extra_hosts:
      - "host.docker.internal:host-gateway"
    restart: unless-stopped 