apiVersion: 1

datasources:
  - name: Loki
    type: loki
    access: proxy
    url: http://loki:3100
    uid: loki
    isDefault: false
    editable: true
    jsonData:
      maxLines: 1000
      # Disable automatic log level detection since we have explicit 'level' label
      derivedFields:
        - datasourceUid: tempo
          name: TraceID
          url: '$${__value.raw}'
          urlDisplayLabel: 'View Trace'
          matcherType: 'label'
          matcherRegex: 'traceId'

  - name: Tempo
    type: tempo
    access: proxy
    url: http://tempo:3200
    uid: tempo
    isDefault: true
    editable: true
    jsonData:
      httpMethod: GET
      tracesToLogsV2:
        datasourceUid: loki
        #tags: ['service_name']
        #mappedTags: 
        #  - key: 'service.name'
        #    value: 'service_name'
        spanStartTimeShift: '-10m'
        spanEndTimeShift: '10m'
        #filterByTraceID: false
        #filterBySpanID: false
        customQuery: true
        query: '{traceId="$${__span.traceId}"}'
      serviceMap:
        datasourceUid: prometheus
      nodeGraph:
        enabled: true
      search:
        hide: false
      lokiSearch:
        datasourceUid: loki

  - name: Prometheus
    type: prometheus
    access: proxy
    url: http://prometheus:9090
    uid: prometheus
    isDefault: false
    editable: true
    jsonData:
      httpMethod: GET
      queryTimeout: 60s
      timeInterval: 15s
      manageAlerts: false
      prometheusType: Prometheus
      prometheusVersion: 2.40.0 