apiVersion: 1

datasources:
  - name: Loki
    type: loki
    access: proxy
    url: http://loki:3100
    uid: loki
    isDefault: false
    editable: true
    jsonData:
      maxLines: 1000
      derivedFields:
        - datasourceUid: tempo
          name: TraceID
          url: '$${__value.raw}'
          urlDisplayLabel: 'View Trace'
          matcherType: 'label'
          matcherRegex: 'traceId'

  - name: Tempo
    type: tempo
    access: proxy
    url: http://tempo:3200
    uid: tempo
    isDefault: true
    editable: true
    jsonData:
      httpMethod: GET
      tracesToLogs:
        datasourceUid: loki
        tags: ['service_name', 'level', 'path', 'userId', 'userName']
        mappedTags: 
          - key: 'service.name'
            value: 'service_name'
        mapTagNamesEnabled: true
        spanStartTimeShift: '5m'
        spanEndTimeShift: '5m'
        filterByTraceID: true
        filterBySpanID: false
        customQuery: '{traceId="${__span.traceId}", service_name="callmiracle"}'
      serviceMap:
        datasourceUid: prometheus
      nodeGraph:
        enabled: true
      search:
        hide: false
      lokiSearch:
        datasourceUid: loki 