export const LANGUAGES = [
  { code: 'en', name: 'English' },
  { code: 'ru', name: 'Russian - Русский' },
  { code: 'es', name: 'Spanish - Español' },
  { code: 'fr', name: 'French - Français' },
  { code: 'de', name: 'German - Deutsch' },
  { code: 'it', name: 'Italian - Italiano' },
  { code: 'pt', name: 'Portuguese - Português' },
  { code: 'pl', name: 'Polish - Polski' },
  { code: 'uk', name: 'Ukrainian - Українська' },
  { code: 'hi', name: 'Hindi - हिन्दी' },
  { code: 'bn', name: 'Bengali - বাংলা' },
  { code: 'pa', name: 'Punjabi - ਪੰਜਾਬੀ' },
  { code: 'te', name: 'Telugu - తెలుగు' },
  { code: 'mr', name: 'Marathi - मराठी' },
  { code: 'ta', name: 'Tamil - தமிழ்' },
  { code: 'gu', name: 'Gujarati - ગુજરાતી' },
  { code: 'kn', name: 'Kannada - ಕನ್ನಡ' },
  { code: 'ml', name: 'Malayalam - മലയാളം' },
  { code: 'zh', name: 'Chinese (Simplified) - 简体中文' },
  { code: 'zh-TW', name: 'Chinese (Traditional) - 繁體中文' },
  { code: 'ja', name: 'Japanese - 日本語' },
  { code: 'ko', name: 'Korean - 한국어' },
  { code: 'vi', name: 'Vietnamese - Tiếng Việt' },
  { code: 'th', name: 'Thai - ไทย' },
  { code: 'id', name: 'Indonesian - Bahasa Indonesia' },
  { code: 'ms', name: 'Malay - Bahasa Melayu' },
  { code: 'ar', name: 'Arabic - العربية' },
  { code: 'fa', name: 'Persian - فارسی' },
  { code: 'he', name: 'Hebrew - עברית' },
  { code: 'tr', name: 'Turkish - Türkçe' },
  { code: 'nl', name: 'Dutch - Nederlands' },
  { code: 'cs', name: 'Czech - Čeština' },
  { code: 'sv', name: 'Swedish - Svenska' },
  { code: 'da', name: 'Danish - Dansk' },
  { code: 'fi', name: 'Finnish - Suomi' },
  { code: 'el', name: 'Greek - Ελληνικά' },
  { code: 'hu', name: 'Hungarian - Magyar' },
  { code: 'ro', name: 'Romanian - Română' },
  { code: 'sk', name: 'Slovak - Slovenčina' },
  { code: 'bg', name: 'Bulgarian - Български' },
  { code: 'hr', name: 'Croatian - Hrvatski' },
  { code: 'sr', name: 'Serbian - Српски' },
  { code: 'sl', name: 'Slovenian - Slovenščina' },
  { code: 'et', name: 'Estonian - Eesti' },
  { code: 'lv', name: 'Latvian - Latviešu' },
  { code: 'lt', name: 'Lithuanian - Lietuvių' },
  { code: 'ka', name: 'Georgian - ქართული' },
  { code: 'hy', name: 'Armenian - Հայերեն' },
  { code: 'az', name: 'Azerbaijani - Azərbaycan' },
  { code: 'kk', name: 'Kazakh - Қазақ' },
  { code: 'uz', name: 'Uzbek - O\'zbek' },
  { code: 'mn', name: 'Mongolian - Монгол' },
  { code: 'sw', name: 'Swahili - Kiswahili' },
  { code: 'af', name: 'Afrikaans' },
  { code: 'ur', name: 'Urdu - اردو' },
  { code: 'am', name: 'Amharic - አማርኛ' },
  { code: 'ne', name: 'Nepali - नेपाली' },
  { code: 'si', name: 'Sinhala - සිංහල' },
  { code: 'km', name: 'Khmer - ខ្មែរ' },
  { code: 'my', name: 'Burmese - မြန်မာ' }
].sort((a, b) => a.name.localeCompare(b.name));