export const INTERESTS = {
  CHAT: 'CHAT',
  MEET_NEW_PEOPLE: 'MEET_NEW_PEOPLE',
  NEED_SPEAKING_OUT: 'NEED_SPEAKING_OUT',
  PROVIDE_LISTENING: 'PROVIDE_LISTENING',
  MEDITATE_TOGETHER: 'MEDITATE_TOGETHER',
  PRAY_TOGETHER: 'PRAY_TOGETHER',
  NEED_EMOTIONAL_SUPPORT: 'NEED_EMOTIONAL_SUPPORT',
  PROVIDE_EMOTIONAL_SUPPORT: 'PROVIDE_EMOTIONAL_SUPPORT',
  NEED_MENTAL_SUPPORT: 'NEED_MENTAL_SUPPORT',
  PROVIDE_MENTAL_SUPPORT: 'PROVIDE_MENTAL_SUPPORT'
} as const

export type InterestType = keyof typeof INTERESTS

export function getMatchingInterest(interest: string): string {
  switch (interest) {
    case INTERESTS.CHAT: return INTERESTS.CHAT
    case INTERESTS.MEET_NEW_PEOPLE: return INTERESTS.MEET_NEW_PEOPLE
    case INTERESTS.NEED_EMOTIONAL_SUPPORT: return INTERESTS.PROVIDE_EMOTIONAL_SUPPORT
    case INTERESTS.NEED_MENTAL_SUPPORT: return INTERESTS.PROVIDE_MENTAL_SUPPORT
    case INTERESTS.PROVIDE_EMOTIONAL_SUPPORT: return INTERESTS.NEED_EMOTIONAL_SUPPORT
    case INTERESTS.PROVIDE_MENTAL_SUPPORT: return INTERESTS.NEED_MENTAL_SUPPORT
    case INTERESTS.PROVIDE_LISTENING: return INTERESTS.NEED_SPEAKING_OUT
    case INTERESTS.NEED_SPEAKING_OUT: return INTERESTS.PROVIDE_LISTENING
    case INTERESTS.PRAY_TOGETHER: return INTERESTS.PRAY_TOGETHER
    case INTERESTS.MEDITATE_TOGETHER: return INTERESTS.MEDITATE_TOGETHER
    default: return interest
  }
}

export function getAllInterests(): string[] {
  return Object.values(INTERESTS)
} 